# RAILS_ENV=production rails assets:precompile
# docker compose exec app bundle exec rails db:migrate

services:
  app:
    tty: true
    stdin_open: true
    image: crm
    build: .
    env_file: ./.env
    container_name: crm
    hostname: crm
    depends_on:
      - pg
    entrypoint: ["/app/bin/docker-entrypoint"]
#    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
#    volumes:
#      - gems:/usr/local/bundle
#      - .:/app
    ports:
      - "127.0.0.1:3001:3000"
      - "172.17.0.1:3001:3000"
    networks:
      net:
    restart: always

  solid_queue:
    image: crm
    build: .
    env_file: ./.env
    container_name: crm_solid_queue
    hostname: crm_solid_queue
    depends_on:
      - pg
    command: ['bundle', 'exec', 'rails', 'solid_queue:start']
#    volumes:
#      - gems:/usr/local/bundle
#      - .:/app
    networks:
      - net
    restart: unless-stopped

  pg:
    image: postgres:17.7
    container_name: crm_pg
    hostname: crm_pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net
    restart: unless-stopped

volumes:
  db_data:
#  gems:

networks:
  net: