default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', nil) %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: osama_development

test:
  <<: *default
  database: osama_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch('DB_NAME', 'osama_production') %>
  cache:
    <<: *primary_production
    database: osama_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: osama_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: osama_production_cable
    migrations_paths: db/cable_migrate
